### ISSUE TITLE
incorrect usage of Linking.getInitialURL in Readme

### ISSUE THREAD

**Issue by neemur** [flexa/flexa-react-native#1]
I believe this line should be `Linking.getInitialURL().then((url) => url && processUniversalLink(url));` as it is done in https://github.com/flexa/flexa-react-native/blob/release-v1.0.0/example/src/App.tsx#L157.  Linking.getInitialURL does not take any arguments

https://github.com/flexa/flexa-react-native/blob/19a65d555127ba9811cf27528f732c8503c27cd2/README.md?plain=1#L270

**Comment by redsquirrel** [comment]
Thank you for the help, @neemur! 🙌
